library(shiny)
library(bslib)
library(bsicons)
library(data.table)
library(magrittr)
library(stringr)
library(ggplot2)
library(cowplot)
library(ggbeeswarm)
library(RColorBrewer)
library(ggstats)
# library(ffbase)
theme_set(theme_cowplot())
